### ISSUE TITLE
Add ability to run commands after changing the wallpaper.

### ISSUE THREAD

**Issue by ykhan21** [amnweb/yasb#49] opened 2024-10-06 23:27 UTC
**What is the request?.**
Add ability to run a command after changing the wallpaper.

**Why is it useful?**
This would allow you reload apps whose themes rely on the wallpaper, such as pywal and any apps that use pywal.
(https://github.com/eylles/pywal16)
(https://github.com/eylles/pywal16/wiki/Getting-Started)

**How could it be implemented?**
Allow the user to provide an array of strings that represent commands to be run.
E.g.
```yaml
run_after:
    [
        "pywal -n -i path/to/new/wallpaper.jpg", # yasb has to provide this path to the image
        "etc"
    ]
```

**Additional context**
pywal is a utility that generates colorscheme files based on the provided image. Many apps have plugins that pick up the pywal generated colorscheme and apply it.

A simple use of pywal on Windows:
1. `pip3 install pywal16`
2. Run `wal -i /path/to/image.jpg`
3. Open Git Bash and this line to your `~/.bashrc` (with the parenthesis): `(cat ~/.cache/wal/sequences &)`.
4. Restart Git Bash and observe the colorscheme. This colorscheme applies to vim and apps such as fastfetch (`winget install fastfetch`) and duf (`scoop install duf`).
5. You can add this theme to various apps (such as VS Code and several browsers) here: https://github.com/eylles/pywal16/wiki/Customization

**Comment by amnweb** [comment] 2024-10-09 00:54
Seems this is most used on Linux as I can see...? There is also winwall as I can see.  
BTW what is `"etc"` in your example, is the 2nd command to run?

**Comment by ykhan21** [comment] 2024-10-09 19:13
> BTW what is "etc" in your example, is the 2nd command to run?

"etc" is a placeholder for other commands to run. If you wanted to reload apps to pick up the new theme, then you can put other commands that do that here.
You could just limit it to one command:
```yaml
run_after: "pywal -n -i path/to/new/wallpaper.jpg" # yasb has to provide this path to the image
```

> Seems this is most used on Linux...?

Yes, like how status bars a Linux thing.
Pywal is used to customize any application that has a plugin for it such as Chrome (and Chromium based browsers), Discord, Firefox, VS Code, IntelliJ. 

> There is also winwall as I can see.

Winwal uses pywal to style PowerShell. It uses the pywal-generated files.

On Windows, you could try out pywal with bash on Wezterm.
(1) Install Wezterm: `winget install wez.wezterm`
(2) Install Git (if you haven't): `winget install --id Git.Git -e --source winget`
(3) Open cmd and cd to your home (`~`) folder: `cd %USERPROFILE%`.
(4) Run `notepad .wezterm.lua`. This creates a wezterm config file and opens it for editing in notepad.
(5) Paste the following into notepad and save it.
```lua
local wezterm = require "wezterm"
local config = {}

local bash = "C:/Program Files/Git/bin/bash.exe"
-- NOTE: if you installed Git with scoop, set the bash variable to the following instead.
-- local bash = "C:/Users/USERNAME/scoop/apps/git/current/bin/bash/bash.exe"

config.default_prog = { bash, "-i", "-l" }

return config
```
(6) Install pywal: `pip install pywal16`
(7) Generate the pywal colorscheme files in ~/.cache/wal: `wal -n -i /path/to/image.jpg`. (Omit `-n` if you also want pywal to set the wallpaper to this image.)
(8) Open wezterm. It should start with a bash shell. Note: To paste in bash, you should `Ctrl-Shift-V` [source](https://superuser.com/questions/421463/why-does-ctrl-v-not-paste-in-bash-linux-shell).
(9) Run `echo '(cat ~/.cache/wal/sequences &)' >> ~/.bashrc`.
(10) Restart wezterm.
(11) Observe color.
(12) To further observe color, see cli apps like fastfetch (`winget install fastfetch`) (a modern neofetch), btm (`winget install Clement.bottom`) (a modern htop), and yazi (a modern ranger) ([install](https://yazi-rs.github.io/docs/installation#windows)).

**Comment by amnweb** [comment] 2024-10-11 13:07
OK, I think this is what you requested.

```
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "\udb83\ude09"
      image_path: "C:\\Users\\amn\\Pictures"
      change_automatically: false
      update_interval: 60
      run_after: [
        "pywal -n -i {image}",
        "pywal another -i {image}",
        "pywal again -n -i {image}"
      ]
```

Here is a demo, and as you can see, all 3 commands run after the wallpaper is changed.

https://github.com/user-attachments/assets/f750aff1-bba9-48de-96e3-a50d5c2a8546

But I can't test this because I can;t get pywal to work on Windows,

**Comment by ykhan21** [comment] 2024-10-11 17:28
Yes, that is what I'm looking for.
`wal` is the cli command that is installed when you pip install this: https://github.com/eylles/pywal16.
Does `wal` work for you?

**Comment by ykhan21** [comment] 2024-10-11 19:18
Not sure what the problem is.

Is it in this folder?
![image](https://github.com/user-attachments/assets/8827cfe2-3f77-4632-b1be-9e4f36a10043)

I think pip installs exe's to a scripts folder, which depending on the python installation method, may not be on the path.
I believe pip also installs exe's to different locations depending on the access level, so `pip install --user ...` and `pip install ...` is different.

> We definitely need to write a doc/Wiki step by step how to run this, otherwise, we can have too many issues with the question of how to run.

Are you asking for a doc on how to use pywal? Or how to use `run_after`?

**Comment by ykhan21** [comment] 2024-10-11 19:36
It looks like pip installs the package to `site-packages` and the exe to a scripts folder.
If the scripts folder is not on the path, you'll have to add the scripts folder to your path.

You could use `fd` (`winget install sharkdp.fd`) to find it fairly quickly by running: `fd -e exe wal`.

https://stackoverflow.com/questions/62162970/programmatically-determine-pip-user-install-location-scripts-directory
https://docs.python.org/3/library/sysconfig.html#installation-paths

**Comment by amnweb** [comment] 2024-10-11 19:38
> Not sure what the problem is.
> 
> Is `wal.exe` in this folder? ![image](https://private-user-images.githubusercontent.com/51864191/375866106-8827cfe2-3f77-4632-b1be-9e4f36a10043.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NzU1NTgsIm5iZiI6MTcyODY3NTI1OCwicGF0aCI6Ii81MTg2NDE5MS8zNzU4NjYxMDYtODgyN2NmZTItM2Y3Ny00NjMyLWIxYmUtOWU0ZjM2YTEwMDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE5MzQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MTFlNjc1YWM1MDI3NTZhMzg2N2E2OTI4ZjY1MjYxNGQxZWMwOTgxM2QzN2JmZmM5ZTY4ZWVkZDg0YTc3Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HTwHf0aIz7CSUi6QgKLQZdZV12Hz-HKTLZieWq85-fI)
> 
> I think pip installs exe's to a scripts folder which, depending on the python installation method, may not be on the path. I believe pip also installs exe's to different locations depending on the access level, so `pip install --user ...` and `pip install ...` is different.
> 
> > We definitely need to write a doc/Wiki step by step how to run this, otherwise, we can have too many issues with the question of how to run.
> 
> Are you asking for a doc on how to use pywal? Or how to use `run_after`?

Yes, that is strange because `wal.exe` does not exist in the script folder, but when I use venv in that case I can see it, maybe it's a problem on my end, not sure.

> Are you asking for a doc on how to use pywal? Or how to use `run_after`?

For both unfortunately, we need to make a short info on how to use with YASB.

**Comment by amnweb** [comment] 2024-10-11 19:44
I think the problem is because I tested last night to build some modules for Python 3.13 to run YASB and there something is messed. Need to clean all this things.

> It looks like pip installs the package to `site-packages` and the exe to a scripts folder. If the scripts folder is not on the path, you'll have to add the scripts folder to your path.

Already added in env.

**Comment by amnweb** [comment] 2024-10-12 01:06
Please try the Wallpaper widget and let me know, I have tried to run winwal, and it looks like it's working fine.

![image](https://github.com/user-attachments/assets/d977578b-41ce-4043-92f2-4305a7c011a9)

https://github.com/user-attachments/assets/dfa92b58-8f5a-4a60-acc0-cf9ba07c6b60

**Comment by ykhan21** [comment] 2024-10-12 02:12
Thanks, it works as expected with "wal -n -i {image}". I haven't tried it with multiple commands yet. I wonder if yasb will hold if you spam the wallpaper widget against multiple commands that take a little while.

**Comment by amnweb** [comment] 2024-10-12 02:19
> Thanks, it works as expected with "wal -n -i {image}". I haven't tried it with multiple commands yet. I wonder if yasb will hold if you spam the wallpaper widget against multiple commands that take a little while.

All this needs to be tested, I've never used pywal before, so I don't know much about it, but I'd love it if you could make a video of how it works for you.

**Comment by ykhan21** [comment] 2024-10-12 02:32
By the way, pywal originally referred to [this project](https://github.com/dylanaraps/pywal), which is now archived. [pywal16](https://github.com/eylles/pywal16) is a 16 color fork of the original pywal.
I don't think winwal handles 16 colors as it was originally designed for the old pywal.

> > Are you asking for a doc on how to use pywal? Or how to use `run_after`?
> 
> For both unfortunately, we need to make a short info on how to use it with YASB.
> 
> Anyway, I will push this commit tonight or tomorrow so you can test it.

The pywal [README](https://github.com/eylles/pywal16?tab=readme-ov-file#this-project-is-a-16-colors-fork-of-pywal) and [guide](https://github.com/eylles/pywal16/wiki/Getting-Started) are pretty clear, if you want to start there.
From there, you do more complex things with pywal, like theming your editor, browser, and generating multiple palettes from a single image with different color backends.

> All this needs to be tested, I've never used pywal before, so I don't know much about it, but I'd love it if you could make a video of how it works for you.

I don't use pywal all too much. I just use it to theme my bash shell in Wezterm as described above, source the `.cache/wal/colors.sh` so fzf, fd, and whatever else can use `LS_COLORS`, and have my browser set up to use [ChromiumPywal](https://github.com/eylles/pywal16/wiki/Customization#chromium). (I'll have to add a command to `run_after` to regenerate the browser theme.) Most cli tools like yazi automatically pick up the colorscheme if you're using bash.

There's also this video that might help.
https://www.youtube.com/watch?v=Es79N_9BblE

**Comment by amnweb** [comment] 2024-10-12 03:51
This commit should prevent any blocking or crashing when running multiple commands https://github.com/amnweb/yasb/commit/73c6fff868744ae4677413bbbfa7424cf81cf89c; also, while the command is running the button will be disabled so you can click when commands are running in the background.

**Comment by ArtyWaBe** [comment] 2024-10-12 06:34
I am using pywal 16 without any issues with Winwal, pywal16 generates all 16 colors if people want to customize.

**Comment by ykhan21** [comment] 2024-10-12 17:18
Someone could make a PR that gets pywal to generate the colors in a template powershell can use, that way you don't need an extra tool. The original pywal broke setting the wallpaper for Windows, which I think is partly why winwal was create. Now, pywal16 can set the wallpaper on Windows.

https://github.com/eylles/pywal16/tree/master/pywal/templates

**Comment by amnweb** [comment] 2024-10-12 17:48
> Someone could make a PR that gets pywal to generate the colors in a template powershell can use, that way you don't need an extra tool. The original pywal broke setting the wallpaper for Windows, which I think is partly why winwal was created. Now, pywal16 can set the wallpaper on Windows.
> 
> https://github.com/eylles/pywal16/tree/master/pywal/templates

It's not a problem to generate colors, but after that you will need to run another function to update settings.json and that is problem. We are just making YASB use pywal colors if you want you can join us on Discord. Anyway, all will be published on the Wiki page soon.

**Comment by ArtyWaBe** [comment] 2024-10-12 17:59
Winwal already has a windows-terminal.json file as a template. The ps1 injects the color values into the settings.json. Of course you can use something else but frankly it's easier to just use winwal and install pywall16 alongside it. As for YASB itself you can do fine without winwal

**Comment by ykhan21** [comment] 2024-10-12 18:15
Is winwal only used to set the Windows Terminal gui colors?
When I `cat .cache/wal/sequences` in pwsh on Windows Terminal, I get the pywal colors.

**Comment by amnweb** [comment] 2024-10-12 18:20
As I can understand, yes, pywal + terminal support = winwal, so Windows users can use winwal without any problems since they're using the wal command.

**Comment by ArtyWaBe** [comment] 2024-10-12 18:40
Yes, winwal uses the Update-WalTerminal function to do just that mostly.

**Comment by ykhan21** [comment] 2024-10-12 21:21
I see. Also, you could have wal run a script after it finishes.

yasb.config
```yaml
run_after: [
    "wal -n -i {image} -o <post_pywal_script>
]
```

post_pywal.ps1
```sh
#!pwsh

pywalfox update
Update-WalTerminal
# etc
```

Having all post pywal scripts in one place makes it a bit more portable so you could reset your entire theme without yasb.

**Comment by amnweb** [comment] 2024-10-13 01:38
> I see. Also, you could have wal run a script after it finishes.
> 
> yasb.config
> 
> ```yaml
> run_after: [
>     "wal -n -i {image} -o <post_pywal_script>
> ]
> ```
> 
> post_pywal.ps1
> 
> ```shell
> #!pwsh
> 
> pywalfox update
> Update-WalTerminal
> # etc
> ```
> 
> Having all post pywal scripts in one place makes it a bit more portable so you could reset your entire theme without yasb.

Have you tried it? For some reason, pywal won't run PowerShell script as `-o`.

**Comment by ykhan21** [comment] 2024-10-13 02:26
Sorry, I hadn't run it. I get "%1 is not a valid Win32 application".

A quick test shows that the following works.
`wal -i img_path -o ~/programs/post_pywal.cmd`

`~/programs/post_pywal.cmd`:
```cmd
pwsh -c "new-item hello-from-wal.txt"
```

This also works.

`wal -i img_path -o ~/programs/post_pywal.cmd`
`~/programs/post_pywal.cmd`:
```cmd
pwsh "%HOME%/programs/post_pywal.ps1"
```
`~/programs/post_pywal.ps1`:
```ps1
new-item "~/hello-from-wal-2.txt"
```

**Comment by amnweb** [comment] 2024-10-13 10:46
Or simple
```
run_after:
  - "wal -s -t -e -q -n -i {image}",
  - "cmd.exe /c start /min pwsh -WindowStyle Hidden ./yasb.ps1"
```
      
or

```
run_after:
  - "wal -s -t -e -q -n -i {image}",
  - "powershell -WindowStyle Hidden ./yasb.ps1"      
```

Anyway if all is ok we can close this issue ?

**Comment by ykhan21** [comment] 2024-10-13 17:44
Yes, thanks.

**Closed** 2024-10-13 17:54 UTC
Labels: feature-request
